# Generated by Django 6.1 on 2026-09-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biografia', models.TextField(blank=True)),
                ('es_artista', models.BooleanField(default=True)),
                ('especialidades', models.CharField(blank=True, help_text='Ej: Blackwork, Old School', max_length=255)),
                ('foto_url', models.URLField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
