# Generated by Django 6.1 on 2026-09-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_seed_artistas'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Número con código de país, solo dígitos. Ej: 5491122334455. Si se deja vacío, el chatbot ofrece el WhatsApp general del estudio en su lugar.', max_length=30),
        ),
    ]
