# Generated by Django 6.1 on 2026-09-01 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image_ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='disenoia',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disenos_ia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='simulaciontatuaje',
            name='diseno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulaciones', to='image_ai.disenoia'),
        ),
    ]
