# Generated by Django 6.1 on 2026-09-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('privacidad', 'Política de privacidad'), ('terminos-y-condiciones', 'Términos y condiciones de uso del sitio'), ('terminos-del-servicio', 'Términos del servicio de tatuaje'), ('cookies', 'Política de cookies')], max_length=30, unique=True)),
                ('titulo', models.CharField(max_length=150)),
                ('contenido', models.TextField(help_text='Separá cada párrafo con una línea en blanco — así se muestran en la página pública. Es un modelo estándar para la etapa beta: antes de un lanzamiento comercial real convenía que un profesional legal lo revise y lo adapte a tu país.')),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Documento legal',
                'verbose_name_plural': 'Documentos legales',
                'ordering': ['tipo'],
            },
        ),
    ]
