# Generated by Django 6.1 on 2026-09-01 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0002_initial'),
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcontacto',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudcontacto',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_recibidas', to='artists.empleado'),
        ),
        migrations.AddIndex(
            model_name='solicitudcontacto',
            index=models.Index(fields=['estado'], name='contacts_so_estado_53a03b_idx'),
        ),
    ]
