# Generated by Django 6.1 on 2026-09-01 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_seed_artistas'),
        ('contacts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcontacto',
            name='contacto',
            field=models.CharField(blank=True, help_text='Email o teléfono', max_length=120),
        ),
        migrations.AddField(
            model_name='solicitudcontacto',
            name='nombre_contacto',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='solicitudcontacto',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudcontacto',
            name='motivo',
            field=models.TextField(max_length=1000),
        ),
        migrations.AddConstraint(
            model_name='solicitudcontacto',
            constraint=models.CheckConstraint(condition=models.Q(('cliente__isnull', False), models.Q(models.Q(('nombre_contacto', ''), _negated=True), models.Q(('contacto', ''), _negated=True)), _connector='OR'), name='solicitud_tiene_identificacion'),
        ),
    ]
