# Generated by Django 6.1 on 2026-09-01 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(upload_to='obras/')),
                ('zona_cuerpo', models.CharField(blank=True, max_length=60)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='artists.empleado')),
                ('estilo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obras', to='gallery.estilo')),
                ('etiquetas', models.ManyToManyField(blank=True, related_name='obras', to='gallery.etiqueta')),
            ],
            options={
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['estilo'], name='gallery_obr_estilo__7b2f59_idx'), models.Index(fields=['artista'], name='gallery_obr_artista_993a54_idx')],
            },
        ),
    ]
