# Generated by Django 6.1 on 2026-09-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Tinta Vieja', max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('horarios', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('redes_sociales', models.JSONField(blank=True, default=dict)),
                ('politicas', models.TextField(blank=True)),
                ('cuidados', models.TextField(blank=True)),
                ('mensaje_transferencia_ia', models.TextField(default='Claro, para ofrecerte un mejor servicio se te contactará con {artista}. Agradecemos tu paciencia.')),
                ('generacion_ia_habilitada', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Configuración del estudio',
                'verbose_name_plural': 'Configuración del estudio',
            },
        ),
    ]
