# Generated by Django 6.1 on 2026-09-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_seed_configuracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionestudio',
            name='whatsapp_general',
            field=models.CharField(blank=True, help_text='Número con código de país, solo dígitos. Ej: 5491122334455. El chatbot lo ofrece cuando piden hablar con alguien y no hay un artista específico.', max_length=30),
        ),
    ]
