# Generated by Django 6.1 on 2026-09-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_seed_whatsapp_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionestudio',
            name='dias_retencion_historial_citas',
            field=models.PositiveSmallIntegerField(default=30, help_text='Días que una cita terminada permanece visible en el historial (con su foto de resultado, si tiene) antes de borrarse automáticamente.'),
        ),
        migrations.AddField(
            model_name='configuracionestudio',
            name='duracion_sesion_minutos_default',
            field=models.PositiveSmallIntegerField(default=240, help_text='Duración en minutos que se usa por defecto para calcular choques de horario cuando no se especifica una duración distinta para la cita.'),
        ),
        migrations.AddField(
            model_name='configuracionestudio',
            name='max_citas_por_tatuador_mes',
            field=models.PositiveSmallIntegerField(default=3, help_text='Cuántas sesiones puede tener agendadas un mismo tatuador dentro de un mismo mes calendario.'),
        ),
        migrations.AddField(
            model_name='configuracionestudio',
            name='max_sesiones_por_cita',
            field=models.PositiveSmallIntegerField(default=6, help_text='Máximo de sesiones que un cliente puede elegir al reservar un tatuaje en varias partes (evita que alguien pida, por ejemplo, 100 sesiones).'),
        ),
        migrations.AddField(
            model_name='configuracionestudio',
            name='umbral_cita_larga_minutos',
            field=models.PositiveSmallIntegerField(default=240, help_text='Si una sesión ya agendada ese día dura más que esto, no se permite asignarle al tatuador ninguna otra sesión ese mismo día.'),
        ),
    ]
