# Generated by Django 6.1 on 2026-09-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_configuracionestudio_dias_retencion_historial_citas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionestudio',
            name='horizonte_reserva_dias',
            field=models.PositiveSmallIntegerField(default=90, help_text='Hasta cuántos días para adelante se puede agendar una sesión (evita reservas absurdamente lejanas, ej. "dentro de 20 años"). ~90 días = 3 meses.'),
        ),
    ]
