# Generated by Django 6.1 on 2026-09-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_configuracionestudio_horizonte_reserva_dias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionestudio',
            name='redes_sociales',
        ),
        migrations.AddField(
            model_name='configuracionestudio',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto de portada de la home (el local, un artista tatuando, etc.) — se sube directo desde tu computadora. Si se deja vacío, se muestra un espacio reservado.', null=True, upload_to='estudio/'),
        ),
        migrations.AddField(
            model_name='configuracionestudio',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Link completo a tu perfil, ej: https://instagram.com/tuestudio'),
        ),
        migrations.AddField(
            model_name='configuracionestudio',
            name='tiktok_url',
            field=models.URLField(blank=True, help_text='Link completo a tu perfil, ej: https://tiktok.com/@tuestudio'),
        ),
        migrations.AlterField(
            model_name='configuracionestudio',
            name='cuidados',
            field=models.TextField(blank=True, help_text='Se muestra en la home, en la sección "Cuidados post-tatuaje" (el link del pie de página lleva ahí). También lo usa el chatbot para responder sobre cuidados.'),
        ),
    ]
