# Generated by Django 6.1 on 2026-09-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncuestaDiseno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estilo', models.CharField(default='no_se', max_length=80)),
                ('colores', models.CharField(default='no_se', max_length=120)),
                ('tamano', models.CharField(default='no_se', max_length=40)),
                ('posicion_cuerpo', models.CharField(default='no_se', max_length=80)),
                ('tematica', models.TextField(blank=True)),
                ('elementos_adicionales', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ReferenciaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_imagen', models.URLField()),
                ('fuente', models.CharField(blank=True, max_length=255)),
                ('aprobada_por_cliente', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
