# Generated by Django 6.1 on 2026-09-01 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('design_assist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='encuestadiseno',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referenciaimagen',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referenciaimagen',
            name='encuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referencias', to='design_assist.encuestadiseno'),
        ),
        migrations.AddIndex(
            model_name='referenciaimagen',
            index=models.Index(fields=['cliente'], name='design_assi_cliente_646b7f_idx'),
        ),
    ]
