# Generated by Django 6.1 on 2026-09-07 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0005_seed_whatsapp'),
        ('gallery', '0002_seed_estilos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sesiones', models.PositiveSmallIntegerField(default=1, help_text='Cuántos encuentros necesita este tatuaje (tope fijado por el gerente).')),
                ('costo', models.DecimalField(blank=True, decimal_places=2, help_text='Se completa cuando el estudio cotiza el trabajo — puede quedar vacío al reservar.', max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('TERMINADA', 'Terminada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('fecha_finalizada', models.DateTimeField(blank=True, help_text='Se completa sola al marcar la cita como terminada. A partir de acá se cuenta el mes que queda en el historial antes del borrado automático.', null=True)),
                ('foto_resultado', models.ImageField(blank=True, null=True, upload_to='citas_resultados/')),
                ('resultado_publicado_portafolio', models.BooleanField(default=False, help_text='Si el tatuador decidió publicar la foto en su portafolio público, queda una copia en Obra (apps.gallery) y esta marca evita duplicarla.')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to=settings.AUTH_USER_MODEL)),
                ('estilo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='gallery.estilo')),
                ('obra_publicada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cita_origen', to='gallery.obra')),
                ('tatuador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='artists.empleado')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-creada'],
            },
        ),
        migrations.CreateModel(
            name='SesionCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(help_text='1ra, 2da, 3ra sesión... de esta cita.')),
                ('inicio', models.DateTimeField()),
                ('duracion_minutos', models.PositiveSmallIntegerField(default=240)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='appointments.cita')),
            ],
            options={
                'verbose_name': 'Sesión de cita',
                'verbose_name_plural': 'Sesiones de citas',
                'ordering': ['numero'],
            },
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['estado'], name='appointment_estado_02daa0_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['tatuador'], name='appointment_tatuado_d46d99_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['fecha_finalizada'], name='appointment_fecha_f_1e1241_idx'),
        ),
        migrations.AddIndex(
            model_name='sesioncita',
            index=models.Index(fields=['inicio'], name='appointment_inicio_6f6696_idx'),
        ),
        migrations.AddIndex(
            model_name='sesioncita',
            index=models.Index(fields=['estado'], name='appointment_estado_1e5081_idx'),
        ),
        migrations.AddConstraint(
            model_name='sesioncita',
            constraint=models.UniqueConstraint(fields=('cita', 'numero'), name='sesion_numero_unico_por_cita'),
        ),
    ]
